### ISSUE TITLE
CT: Cannot read property 'dataStream' of undefined

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gases-intro#6]
```
gases-intro : phet-io-mirror-inputs-fuzz : require.js : load
Uncaught Error: Uncaught TypeError: Cannot read property 'dataStream' of undefined
TypeError: Cannot read property 'dataStream' of undefined
    at BooleanProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1582831044673/tandem/js/PhetioObject.js:402:21)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1582831044673/axon/js/Property.js:262:41)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1582831044673/axon/js/Property.js:175:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1582831044673/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1582831044673/gases-intro/js/gases-intro-main.js?bust=1582835132193:27:58
id: Bayes Chrome
Approximately 2/27/2020, 12:17:24 PM
```

Related code in gases-intro-main.js:

```js
  /**
   * If the pressureNoise query parameter was not specified in the URL, then set it to false.
   * The default is true for Gas Properties, and this is a workaround to change that default
   * for this derivative sim.  See https://github.com/phetsims/gases-intro/issues/3
   */
  if ( !QueryStringMachine.containsKey( 'pressureNoise' ) ) {
    GasPropertiesGlobalOptions.pressureNoiseProperty.value = false;
  }
```

With ES6 modules, any changes to instrumented Properties must take place after PhET-iO has been initialized. Try moving this inside `SimLauncher.launch`.

**Comment by pixelzoom** [comment]
Description of `phet-io-mirror-inputs-fuzz` in continuous-server.js:

```
snapshot.testQueue.push( {
  count: 0,
  snapshotName: snapshotName,
  test: [ phetioRepo, 'phet-io-mirror-inputs-fuzz', 'require.js' ],
  url: 'sim-test.html?url=' + encodeURIComponent( `../../${snapshotName}/phet-io-wrappers/mirror-inputs/?sim=${phetioRepo}&phetioDebug&fuzz&postMessageToParent` )
} );
```

**Comment by pixelzoom** [comment]
I can't reproduce this manually with http://localhost/~cmalley/GitHub/phet-io-wrappers/mirror-inputs/?sim=gases-intro&phetioDebug&fuzz&postMessageToParent.   So I can't confirm whether moving code inside of `SimLauncher.launch` fixes the problem.

@samreid thoughts?

**Comment by pixelzoom** [comment]
Ah, never mind. I was still on pre-migration branches.

**Comment by pixelzoom** [comment]
Fixed in the above commit. Verified before and after with http://localhost/~cmalley/GitHub/phet-io-wrappers/mirror-inputs/?sim=gases-intro&phetioDebug&fuzz&postMessageToParent. 

I'll leave this open for a couple of CT cycles to confirm.

**Comment by pixelzoom** [comment]
This appears to be fixed on CT, and we're back to failing on https://github.com/phetsims/gas-properties/issues/178. 

Closing.
