### ISSUE TITLE
CT invalid temperature null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gases-intro#8]
```
gases-intro : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/gases-intro/gases-intro_en.html?continuousTest=%7B%22test%22%3A%5B%22gases-intro%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1604652787156%22%2C%22timestamp%22%3A1604675421557%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid temperature: null
Error: Assertion failed: invalid temperature: null
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/assert/js/assert.js:22:13)
at ParticleSystem.setTemperature (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/gas-properties/js/common/model/ParticleSystem.js:332:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/gas-properties/js/common/model/IdealGasLawModel.js:218:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/axon/js/TinyEmitter.js:71:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/axon/js/Property.js:280:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/axon/js/Property.js:178:14)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/axon/js/DerivedProperty.js:77:19)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/axon/js/TinyEmitter.js:71:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/axon/js/Property.js:280:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604652787156/axon/js/Property.js:178:14)
id: Bayes Chrome
Snapshot from 11/6/2020, 1:53:07 AM
```

**Comment by pixelzoom** [comment]
Duplicate of https://github.com/phetsims/gas-properties/issues/168.  Closing.
